JoinMessage: '&6&l%player% &r&ahas joined the server!'
LeaveMessage: '&6&l%player% &r&chas left the server!'
MOTD: '          &6&lEnchanted Network - 1.18.2§r\n                &aVehicle Update Out Now!'
