name: Enchanted
version: '${project.version}'
main: net.enchanted.enchanted.Enchanted
api-version: 1.18
authors: [ NewGuitarWhoDis ]
depend: [ProtocolLib]
commands:
  createvehicle:
    description: vehicle command
    usage: /[command]
  createnpc:
    description: creates custom npc
  resettires:
    description: resets tire wear
  race:
    description: F1 Races
  safetycar:
    description: Safety Car
  vehicle:
    description: Vehicle stuff
